apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "nginx-1"
  namespace: "default"
  labels:
    app: "nginx-1"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "nginx-1"
  template:
    metadata:
      labels:
        app: "nginx-1"
    spec:
      containers:
      - name: "nginx-1"
        image: "nginx:latest"
        ports:
        - containerPort: 443
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-1
spec:
  selector:
    app.kubernetes.io/name: nginx-1
  type: LoadBalancer  
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
